name: build_resource_pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create resource pack zip
        run: |
          zip -r simulacrum_pack.zip ./* -x ".git/*" -x ".github/*"

      - name: Create or update latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Resource Pack
          files: simulacrum_pack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
